

// SHOE CATEGORY OF THE NEW ARRIVAL DATA 

const ShoeCategory = [
    {
        id: 0,
        image: 'https://m.media-amazon.com/images/I/617SdHv8FGL._UY535_.jpg',
        image2: 'https://m.media-amazon.com/images/I/61sx2DMxfuL._UY500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/619HNpxwdGL._UY500_.jpg',
        image4: 'https://m.media-amazon.com/images/I/61Y0aIqjM7L._UY500_.jpg',
        image5: 'https://m.media-amazon.com/images/I/61ZxiXY4emL._UY500_.jpg',
        price: '₹995.00',  
        name: 'RazMaz',
        description: 'Women Shoe',
        productType: 'shoe',
        type: 'women',
    },
    {
        id: 1,
        image: 'https://m.media-amazon.com/images/I/51oABMaCNhL._UY535_.jpg',
        image2: 'https://m.media-amazon.com/images/I/513DVH+gHWL._UY500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/51BYilo+01L._UY500_.jpg',
        image4: 'https://m.media-amazon.com/images/I/51BYilo+01L._UY500_.jpg',
        image5: 'https://m.media-amazon.com/images/I/51oABMaCNhL._UY500_.jpg',
        price: '₹10,999.00',  
        name: 'Stupmary',
        description: 'Women Over the Knee Boots Thigh High Platform Bootie Heeled Party Rear Zip Lace Up Botas',
        productType: 'shoe',
        type: 'women',
    },
    {
        id: 2,
        image: 'https://m.media-amazon.com/images/I/81ewDmoYxkL._UX695_.jpg',
        image2: 'https://m.media-amazon.com/images/I/813Zj2WGbGL._UX500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/813DzrfgyNL._UX500_.jpg',
        image4: 'https://m.media-amazon.com/images/I/81sT02BEwzL._UX500_.jpg',
        image5: 'https://m.media-amazon.com/images/I/61UbJ0Y420L._UX500_.jpg',
        price: '₹3,359.00',  
        name: 'RazMaz',
        description: 'Skechers Womens Skech-air Dynamight Sneaker',
        productType: 'shoe',
        type: 'women',
    },
    {
        id: 3,
        image: 'https://m.media-amazon.com/images/I/81JJUF5I1BL._UX695_.jpg',
        image2: 'https://m.media-amazon.com/images/I/811qeiEgZNL._UX500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/81VG8z+pRZL._UX500_.jpg',
        image4: 'https://m.media-amazon.com/images/I/819pb2PX7pL._UY500_.jpg',
        image5: 'https://m.media-amazon.com/images/I/61dw6RwfS4L._UX500_.jpg',
        price: '₹3,188.00',  
        name: 'Sketcher',
        description: "Skechers Womens Skech-air Dynamight-Nature's Sneaker",
        productType: 'shoe',
        type: 'women',
    },
    {
        id: 4,
        image: 'https://m.media-amazon.com/images/I/81kx3xj01zL._UX695_.jpg',
        image2: 'https://m.media-amazon.com/images/I/81LVsNIg6JL._UX500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/81tbriZGNHL._UX500_.jpg',
        image4: 'https://m.media-amazon.com/images/I/81a6uot-IrL._UX500_.jpg',
        image5: 'https://m.media-amazon.com/images/I/71A2AWuaGoL._UX500_.jpg',
        price: '₹2,999.00',  
        name: 'Puma Womens',
        description:"Puma Womens Better Foam Prowl Slip WN's Walking Shoe",
        productType: 'shoe',
        type: 'women',
    },
    {
        id: 5,
        image: 'https://m.media-amazon.com/images/I/517K1kVuqfL._UX625_.jpg',
        image2: 'https://m.media-amazon.com/images/I/5108XEP9joL._UX500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image4: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image5: 'https://m.media-amazon.com/images/I/51LY25AWR8L._UY500_.jpg',
        price: '₹699.00',  
        name: 'Dazibao',
        description: 'Casual High Ankle Heel Boots Fashion Jeans Shoe Boot For Women and Girls',
        productType: 'shoe',
        type: 'women',
    },
    {
        id: 6,
        image: 'https://m.media-amazon.com/images/I/61oCUNkH4ZS._SY625._SX._UX._SY._UY_.jpg',
        image2: 'https://m.media-amazon.com/images/I/51p8SBa5H2L._SY500._SX._UX._SY._UY_.jpg',
        image3: 'https://m.media-amazon.com/images/I/61BjsnZwGiS._SY625._SX._UX._SY._UY_.jpg',
        image4: 'https://m.media-amazon.com/images/I/51BtkMRioZS._SY625._SX._UX._SY._UY_.jpg',
        image5: '	https://m.media-amazon.com/images/I/51Y45aU3sPS._SY625._SX._UX._SY._UY_.jpg',
        price: '₹770.00',  
        name: 'Marc Loire',
        description: "Women's Fashion Pointed Stiletto Heel Pump Shoes for Party and Formal Occasions",
        productType: 'shoe',
        type: 'women',
    },
    {
        id: 7,
        image: 'https://m.media-amazon.com/images/I/61kafNaOSFL._UX695_.jpg',
        image2: 'https://m.media-amazon.com/images/I/6150n4DKeNL._UX500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image4: 'https://m.media-amazon.com/images/I/51scQY1qZlL._UY535_.jpg',
        image5: 'https://m.media-amazon.com/images/I/716nItUNBRL._UY575_.jpg',
        price: '₹1,949.00',  
        name: 'Chere',
        description: ' Caramel Pump high Heels for Women’s | Comfortable Sandals for Casual, Party and Formal Occasions',
        productType: 'shoe',
        type: 'women',
    },
    {
        id: 8,
        image: 'https://m.media-amazon.com/images/I/51QGPQJSIJL._UY535_.jpg',
        image2: 'https://m.media-amazon.com/images/I/61Wlk52ZukL._UY500_.jpg',
        image3: '	https://m.media-amazon.com/images/I/617bKHGr+qL._UY500_.jpg',
        image4: '	https://m.media-amazon.com/images/I/41x3vGyUNxL._UY500_.jpg',
        image5: '	https://m.media-amazon.com/images/I/51x7TySmubL._UY500_.jpg',
        price: '₹19,522.00',  
        name: 'Chelsea & Zoe',
        description: 'Casual High Ankle Heel Boots Fashion Jeans Shoe Boot For Women and Girls',
        productType: 'shoe',
        type: 'women',
    },
    {
        id: 9,
        image: 'https://m.media-amazon.com/images/I/71piCb2U1rL._UX500_.jpg',
        image2: 'https://m.media-amazon.com/images/I/61elLtEKDPL._UY500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/71dESYPn0EL._UX500_.jpg',
        image4: 'https://m.media-amazon.com/images/I/71atjt3jp2L._UX500_.jpg',
        image5: 'https://m.media-amazon.com/images/I/71edLK36uSL._UX500_.jpg',
        price: '₹1,017.00',  
        name: "Hirel's",
        description: "HiREL'S Men Formal Shoes",
        productType: 'shoe',
        type: 'men',
    },
    {
        id: 10,
        image: 'https://m.media-amazon.com/images/I/61EhSgAKYDL._UY535_.jpg',
        image2: 'https://m.media-amazon.com/images/I/61-l-KaPpEL._UY575_.jpg',
        image3: 'https://m.media-amazon.com/images/I/61uqgiLhcUL._UY575_.jpg',
        image4: 'https://m.media-amazon.com/images/I/61F-BN-3WwL._UY575_.jpg',
        image5: 'https://m.media-amazon.com/images/I/61rOC-w1HYL._UY575_.jpg',
        price: '₹929.00',  
        name: 'SIR CORBETT',
        description: "Men's Tan and Black Synthetic Formal Monk Strap Shoes",
        productType: 'shoe',
        type: 'men',
    },
    {
        id: 11,
        image: 'https://static.nike.com/a/images/t_prod_ss/w_960,c_limit,f_auto/4e46bd9c-791f-4a81-8899-c6860bb8de08/air-jordan-1-next-chapter-dv1748-601-release-date.jpg',
        image2: 'https://static.nike.com/a/images/t_prod_ss/w_960,c…jordan-1-next-chapter-dv1748-601-release-date.jpg',
        image3: 'https://static.nike.com/a/images/t_prod_sc/w_960,c…jordan-1-next-chapter-dv1748-601-release-date.jpg',
        image4: 'https://static.nike.com/a/images/t_prod_ss/w_960,c…jordan-1-next-chapter-dv1748-601-release-date.jpg',
        image5: 'https://static.nike.com/a/images/t_prod_ss/w_960,c…jordan-1-next-chapter-dv1748-601-release-date.jpg',
        price: '₹18,395.00',  
        name: 'Nike SNKRS',
        description: "Air Jordon 1 'Next Chapter",
        productType: 'shoe',
        type: 'men',
    },
    {
        id: 12,
        image: 'https://m.media-amazon.com/images/I/51cSS91ny+L._UY535_.jpg',
        image2: 'https://m.media-amazon.com/images/I/51G8ie4dR2L._UY500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/61QTeFCla0L._UY500_.jpg',
        image4: 'https://m.media-amazon.com/images/I/514THE-DP-L._UY500_.jpg',
        image5: 'https://m.media-amazon.com/images/I/51E2O5LCpwL._UY500_.jpg',
        price: '₹4,841.00',  
        name: 'Nike',
        description: 'Nike Mens Precision Vi Running Shoe',
        productType: 'shoe',
        type: 'men',
    },
    {
        id: 5,
        image: 'https://m.media-amazon.com/images/I/517K1kVuqfL._UX625_.jpg',
        image2: 'https://m.media-amazon.com/images/I/5108XEP9joL._UX500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image4: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image5: 'https://m.media-amazon.com/images/I/51LY25AWR8L._UY500_.jpg',
        price: '₹699.00',  
        name: 'Dazibao',
        description: 'Casual High Ankle Heel Boots Fashion Jeans Shoe Boot For Women and Girls',
        productType: 'shoe',
        type: 'women',
    },
    {
        id: 14,
        image: 'https://m.media-amazon.com/images/I/71uyOvox4JL._UY535_.jpg',
        image2: 'https://m.media-amazon.com/images/I/71hmTqq7ufL._UY500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/71yQXwnI7hL._UY500_.jpg',
        image4: 'https://m.media-amazon.com/images/I/71Q2gXONROL._UY500_.jpg',
        image5: 'https://m.media-amazon.com/images/I/61gd9iBrARL._UY500_.jpg',
        price: '₹699.00',  
        name: 'Bacca Bucci',
        description: 'Casual High Ankle Heel Boots Fashion Jeans Shoe Boot For Women and Girls',
        productType: 'shoe',
        type: 'men',
    },
    {
        id: 15,
        image: '	https://m.media-amazon.com/images/I/81+nxbyxocL._UY500_.jpg',
        image2: '	https://m.media-amazon.com/images/I/712-ZPngfDL._UY500_.jpg',
        image3: '	https://m.media-amazon.com/images/I/71Epj8eZnzL._UX500_.jpg',
        image4: '	https://m.media-amazon.com/images/I/81EGni2wfKL._UY500_.jpg',
        image5: '	https://m.media-amazon.com/images/I/816WK8SJ-XL._UY500_.jpg',
        price: '₹998.00',  
        name: 'Generic',
        description: "Women's Fashion Sandal",
        productType: 'shoe',
        type: 'women',
    },
    {
        id: 16,
        image: 'https://m.media-amazon.com/images/I/41wjgQRRd2L._SY500._SX._UX._SY._UY_.jpg',
        image2: 'https://m.media-amazon.com/images/I/41as27L3yvL._SY500._SX._UX._SY._UY_.jpg',
        image3: 'https://m.media-amazon.com/images/I/5101TEGLkmL._SY500._SX._UX._SY._UY_.jpg',
        image4: 'https://m.media-amazon.com/images/I/41lgNErw0VL._SY500._SX._UX._SY._UY_.jpg',
        image5: 'https://m.media-amazon.com/images/I/31ecByqrb7L.._SX._UX._SY._UY_.jpg',
        price: '₹8,491.00',  
        name: 'Nike',
        description: 'Nike mens Nike Air Winflo 9 Mens Running Shoes Running Shoes',
        productType: 'shoe',
        type: 'men',
    },
    {
        id: 5,
        image: 'https://m.media-amazon.com/images/I/517K1kVuqfL._UX625_.jpg',
        image2: 'https://m.media-amazon.com/images/I/5108XEP9joL._UX500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image4: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image5: 'https://m.media-amazon.com/images/I/51LY25AWR8L._UY500_.jpg',
        price: '₹699.00',  
        name: 'Dazibao',
        description: 'Casual High Ankle Heel Boots Fashion Jeans Shoe Boot For Women and Girls',
        productType: 'shoe',
        type: 'women',
    },
    {
        id: 5,
        image: 'https://m.media-amazon.com/images/I/517K1kVuqfL._UX625_.jpg',
        image2: 'https://m.media-amazon.com/images/I/5108XEP9joL._UX500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image4: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image5: 'https://m.media-amazon.com/images/I/51LY25AWR8L._UY500_.jpg',
        price: '₹699.00',  
        name: 'Dazibao',
        description: 'Casual High Ankle Heel Boots Fashion Jeans Shoe Boot For Women and Girls',
        productType: 'shoe',
        type: 'women',
    },
    {
        id: 5,
        image: 'https://m.media-amazon.com/images/I/517K1kVuqfL._UX625_.jpg',
        image2: 'https://m.media-amazon.com/images/I/5108XEP9joL._UX500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image4: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image5: 'https://m.media-amazon.com/images/I/51LY25AWR8L._UY500_.jpg',
        price: '₹699.00',  
        name: 'Dazibao',
        description: 'Casual High Ankle Heel Boots Fashion Jeans Shoe Boot For Women and Girls',
        productType: 'shoe',
        type: 'women',
    },

    {
        id: 5,
        image: 'https://m.media-amazon.com/images/I/517K1kVuqfL._UX625_.jpg',
        image2: 'https://m.media-amazon.com/images/I/5108XEP9joL._UX500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image4: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image5: 'https://m.media-amazon.com/images/I/51LY25AWR8L._UY500_.jpg',
        price: '₹699.00',  
        name: 'Dazibao',
        description: 'Casual High Ankle Heel Boots Fashion Jeans Shoe Boot For Women and Girls',
        productType: 'shoe',
        type: 'women',
    },
    {
        id: 5,
        image: 'https://m.media-amazon.com/images/I/517K1kVuqfL._UX625_.jpg',
        image2: 'https://m.media-amazon.com/images/I/5108XEP9joL._UX500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image4: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image5: 'https://m.media-amazon.com/images/I/51LY25AWR8L._UY500_.jpg',
        price: '₹699.00',  
        name: 'Dazibao',
        description: 'Casual High Ankle Heel Boots Fashion Jeans Shoe Boot For Women and Girls',
        productType: 'shoe',
        type: 'women',
    },
    {
        id: 5,
        image: 'https://m.media-amazon.com/images/I/517K1kVuqfL._UX625_.jpg',
        image2: 'https://m.media-amazon.com/images/I/5108XEP9joL._UX500_.jpg',
        image3: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image4: 'https://m.media-amazon.com/images/I/517w7hE4E8L._UY575_.jpg',
        image5: 'https://m.media-amazon.com/images/I/51LY25AWR8L._UY500_.jpg',
        price: '₹699.00',  
        name: 'Dazibao',
        description: 'Casual High Ankle Heel Boots Fashion Jeans Shoe Boot For Women and Girls',
        productType: 'shoe',
        type: 'women',
    },

    
];

export default ShoeCategory;